apiVersion: v1
appVersion: "0.0.1"
description: A Helm chart for arce
name: arce
version: 0.0.1
dependencies:
  - name: postgresql
    version: 8.6.4
    repository: https://charts.helm.sh/stable
    condition: postgresql.enabled
