stages:
  - build
  - test
  - deploy

before_script:
  - export TAG=${CI_COMMIT_SHORT_SHA}
  - export BRANCH=${CI_COMMIT_REF_NAME}
  - export REGISTRY_HOST=${CI_REGISTRY}
  - export REGISTRY_URI="/${CI_PROJECT_PATH}"
  - touch .env.development

base:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - sc build -s base
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - sc push -s base
  when: manual
  tags:
    - local

build:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - sc build
    - sc push
    - docker tag $CI_REGISTRY_IMAGE:$TAG $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  tags:
    - local


test:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  services:
    - name: postgres:11.1
    - name: solr:latest
      entrypoint: ["docker-entrypoint.sh", "solr-precreate", "test"]
  script:
    - echo "$POSTGRES_HOST"
    - cd /home/app/webapp && bundle exec rake db:create db:schema:load spec
  variables:
    GIT_STRATEGY: none
    POSTGRES_DB: arce
    POSTGRES_HOST: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_USER: postgres
    SOLR_URL: http://solr:8983/solr/test
    TEST_DB: arce
  tags:
    - docker

staging:
  stage: deploy
  type: deploy
  script:
    - "keybase status | grep 'Logged in:     no' && keybase oneshot"
    - ./chart/bin/decrypt staging
    - ./chart/bin/deploy staging $CI_COMMIT_SHORT_SHA
  after_script:
    - rm -f ./chart/*-values.yaml
    - keybase logout
  when: manual
  tags:
    - local

production:
  stage: deploy
  type: deploy
  script:
    - export KUBECONFIG=$KUBECONFIG_PALS
    - "keybase status | grep 'Logged in:     no' && keybase oneshot"
    - ./chart/bin/decrypt production
    - ./chart/bin/deploy production $CI_COMMIT_SHORT_SHA
  after_script:
    - rm -f ./chart/*-values.yaml
    - keybase logout
  when: manual
  tags:
    - local
