version: '2'
services:
  postgres:
    image: postgres
    env_file:
      - .env
      - .env.production
    ports:
      - "5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  solr:
    image: "${REGISTRY_HOST}${REGISTRY_URI}/solr:latest"
    restart: unless-stopped
    ports:
      - "8983"
    labels:
      rap.host: ${SITE_URI}
      rap.le_host: ${SITE_URI}
      rap.le_test: true
      io.rancher.container.pull_image: always
    env_file:
      - .env.production
      - .env
    volumes:
      - solr:/solr_home


  web:
    image: "${REGISTRY_HOST}${REGISTRY_URI}:${TAG}"
    restart: unless-stopped
    ports:
      - "80"
    labels:
      rap.host: ${SITE_URI}
      rap.le_host: ${SITE_URI}
      rap.le_test: true
      io.rancher.container.pull_image: always
    env_file:
      - .env
      - .env.production
    depends_on:
      - postgres
      - solr

  # NOTE: THIS IS FOR SCALING OUT IMPORT/PROCESS (SPEICIFCALLY OF PEAKS)
  # EVEN IF YOU KILL THIS CONTAINER, THERE IS A SINGLE WORKER IN THE WEB CONTAINER
  worker:
    image: "${REGISTRY_HOST}${REGISTRY_URI}:${TAG}"
    restart: unless-stopped
    command: bin/delayed_job run
    labels:
      io.rancher.container.pull_image: always
    env_file:
      - .env
      - .env.production
    depends_on:
      - postgres
      - solr

volumes:
  postgres:
  solr:
