---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.rails-env.name" . }}
data:
  POSTGRES_HOST: {{ template "app.postgres.name" . }}
  SOLR_BASE_URL: http://{{ template "app.solr.name" . }}:8983/solr
  SOLR_URL: http://{{ template "app.solr.name" . }}:8983/solr/blacklight-core
{{- range $key, $value := .Values.env.configmap }}
  {{ $key }}: "{{ $value }}"
{{- end }}
