---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.rails-env.name" . }}-cm
data:
  POSTGRES_HOST: {{ template "app.postgres.name" . }}
{{- range $key, $value := .Values.env.configmap }}
  {{ $key }}: "{{ $value }}"
{{- end }}