---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.rails-env.name" . }}
data:
  DATABASE_HOST: {{ template "app.postgres.name" . }}
  SOLR_URL: http://{{ template "app.solr.name" . }}:8983/solr/
{{- range $key, $value := .Values.env.configmap }}
  {{- if eq $.Values.env.configmap.SETTINGS__MULTITENANCY__ENABLED false }}
  {{- if and (ne $key "SETTINGS__MULTITENANCY__ADMIN_HOST") (ne $key "SETTINGS__MULTITENANCY__DEFAULT_HOST") }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
  {{- else }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}
