---
{{- $releaseName := .Release.Name -}}
{{- $serviceName := include "app.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "app.web.name" . }}-in
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - backend:
          serviceName: {{ printf "%s" $serviceName | trunc 63 | trimSuffix "-" }}-web
          servicePort: 80
  {{- end }}
  {{- if .Values.ingress.tlsSecretName }}
  tls:
  - hosts:
      {{- range .Values.ingress.hosts }}
      - {{ . | quote }}
      {{- end }}
    secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end -}}