name: 'Build Test Lint'
run-name: Build Test Lint of ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    uses: scientist-softserv/actions/.github/workflows/build.yaml@updates-to-v14
    secrets: inherit
    with:
      platforms: 'linux/amd64'
      webTarget: web
      workerTarget: web
      solrTarget: solr
  test:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/test.yaml@updates-to-v14
    with:
      confdir: '/home/app/webapp/solr/conf'
      webTarget: web
      workerTarget: web
      solrTarget: solr
      setup_db_cmd: 'RAILS_ENV=test PASSENGER_APP_ENV=test'
      rspec_cmd:  'bundle exec rspec'
  lint:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@updates-to-v14
    with:
      webTarget: web
      workerTarget: web
      solrTarget: solr