name: "Build Lint"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    uses: scientist-softserv/actions/.github/workflows/build.yaml@v0.0.1
    with:
      worker: true
      target: hyrax-base
      workerTarget: hyrax-worker

  lint:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@v0.0.1
    with:
      worker: true
      target: hyrax-base
      workerTarget: hyrax-worker
      # tag: deca90d9
